### ISSUE TITLE
fatal: Could not parse object 'b503d24cdf56abf8c0d66d438ccac28969f01670'.

### ISSUE THREAD

**Issue by jasc76** [yokrysty/docker-pulseview-cc-mingw#2]
I tried it with you release container
Imported it with docker load -i 
put the .fw file in the same directory where all the .cmd files are and ran build_pulseview_incl_fx3_installer.cmd

```
/root/mxe-git/usr/bin/install -c -m 644 libserialport.pc '/root/sr_mingw_release_64/lib/pkgconfig'
component libsigrok ...
Cloning into 'libsigrok'...
remote: Enumerating objects: 583, done.
remote: Counting objects: 100% (583/583), done.
remote: Compressing objects: 100% (553/553), done.
remote: Total 583 (delta 95), reused 194 (delta 21), pack-reused 0
Receiving objects: 100% (583/583), 1.57 MiB | 6.61 MiB/s, done.
Resolving deltas: 100% (95/95), done.
fatal: Could not parse object 'b503d24cdf56abf8c0d66d438ccac28969f01670'.
```

**Comment by yokrysty** [comment]
oh yes my bad, fixed now, made a new release
what was the problem: i am using a specific git hash when cloning libsigrok to make sure there are no conflicts when applying patches, but i was cloning without history and when i put it all together, that git hash was the most recent commit and it worked fine

**Comment by jasc76** [comment]
THX !!!
